### PR TITLE
fix(azure-iot-device):registration id and indentation fix

### PR DESCRIPTION
**Pull request by olivakar**

### CODE REVIEW

**Comment by olivakar** [comment]
https://github.com/Azure/azure-iot-sdk-python/issues/691

**Comment by olivakar** [comment]
https://github.com/Azure/azure-iot-sdk-python/issues/667

**Comment by cartertinney** [comment]
Where is the indentation fix?

**Review by cartertinney — APPROVED** [review]
:shipit:

**Pull request merged**
