### PR TITLE
reduce noise at level=logging.INFO by moving messages to logging.DEBUG

### PR DESCRIPTION
**Pull request by BertKleewein**
Based on feedback left by @LouanDuToitS3 at https://github.com/Azure/azure-iot-sdk-python/issues/148#issuecomment-527037904

### CODE REVIEW

**Comment by cartertinney** [comment]
Good idea, this was a change we were definitely due for.

**Comment by LouanDuToitS3** [comment]
Hi, @BertKleewein 
I've tried the latest release, preview 13 ( 01caaf7). But I still find the logs to be very verbose under normal circumstances. Did this change make it into the release?

**Comment by BertKleewein** [comment]
Hi @LouanDuToitS3,

This fix did make it into the release.  We reduced the number of messages, but it sounds like we didn't reduce it enough for your scenario.

Would it is help to limit our messages to just errors?
```
 logging.getLogger("azure.iot.device").setLevel(level=logging.ERROR)
```
To reduce it even further, you could even set it to logging.CRITICAL, which would remove all messages from our component.

**Comment by LouanDuToitS3** [comment]
Hi @BertKleewein 

That is perfect, I did not realise that you used a named logger for the logging. So all good, thanks.

**Pull request merged**
