### PR TITLE
build Python Module on Mac OS

### PR DESCRIPTION
**Pull request by sHorst**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem
Python module does not build on Mac OS

# Description of the solution
I copied the linux version, and changed the parameters to work on Mac OS.

### CODE REVIEW

**Comment by zolvarga** [comment]
@sHorst,

I tested your branch on Mac. The "setup.sh" file in /build_all/mac calling into the C sub-module build_all/mac folder but that is not exists.
Your branch does not contain the modifications you made in C sub-module. 

Please check that in also.

Best Regards,
Zoltan

**Comment by sHorst** [comment]
hey .. i changed that bit in the commit e27bfe1. it now builds the c module directly using cmake. this because the aure-iot-sdk-c guys say they want to go with. So i changed the pull request to only contain changes in this sdk.

**Comment by zolvarga** [comment]
@sHorst 
I know about the ask for cmake (I am one of those "aure-iot-sdk-c guys" :)
But the setup script still should work...

Best Regards,
Zoltan

**Comment by sHorst** [comment]
sorry .. missed the setup.sh .. of course .. i merged the brew install :) but forgot to remove the call :)

**Comment by zolvarga** [comment]
:shipit:

**Comment by zolvarga** [comment]
@sHorst,

I verified your pull request and it worked. (thanks for updating the setup script).
I am accepting the PR.

Thanks for contributing to our repository!

Best Regards,
Zoltan

**Pull request merged**
